import { StyleSheet } from "react-native";

import { adminCommonStyles } from "./global";

export const styles = StyleSheet.create({
  ...adminCommonStyles,
  centerWrap: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
  },
  helper: {
    color: "#a2a7b2",
    fontSize: 14,
  },
  card: {
    flex: 1,
    backgroundColor: "#171a21",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#2b303a",
    padding: 16,
    marginBottom: 12,
  },
  cardContent: {
    paddingBottom: 14,
  },
  sectionCard: {
    backgroundColor: "#1b1f27",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#303642",
    padding: 12,
    marginBottom: 12,
  },
  sectionTitle: {
    marginTop: 4,
    marginBottom: 8,
    fontSize: 16,
    fontWeight: "700",
    color: "#d4d9e2",
  },
  stepperRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 10,
  },
  stepButton: {
    paddingHorizontal: 12,
    height: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#3a4250",
    backgroundColor: "#222833",
    alignItems: "center",
    justifyContent: "center",
  },
  stepButtonActive: {
    borderColor: "#7da2d2",
    backgroundColor: "#2b3a4f",
  },
  stepButtonText: {
    color: "#c6cfde",
    fontSize: 12,
    fontWeight: "600",
  },
  stepButtonTextActive: {
    color: "#edf4ff",
  },
  modePickerRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 8,
    marginBottom: 6,
  },
  modePickerButton: {
    paddingHorizontal: 12,
    height: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#3a4250",
    backgroundColor: "#242a34",
    alignItems: "center",
    justifyContent: "center",
  },
  modePickerButtonActive: {
    borderColor: "#6f8fb7",
    backgroundColor: "#2f3848",
  },
  modePickerButtonText: {
    color: "#c4cad6",
    fontWeight: "600",
    fontSize: 12,
  },
  modePickerButtonTextActive: {
    color: "#d9e4f7",
  },
  formulaGrid: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
    flexWrap: "wrap",
    marginBottom: 8,
  },
  formulaField: {
    gap: 6,
  },
  formulaLabel: {
    fontSize: 13,
    color: "#c6cfde",
    fontWeight: "600",
  },
  formulaWide: {
    minWidth: 260,
    flexGrow: 1,
  },
  formulaCell: {
    minWidth: 120,
  },
  instructionCard: {
    borderWidth: 1,
    borderColor: "#353e4c",
    backgroundColor: "#202733",
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
    gap: 3,
  },
  instructionTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#d2d8e3",
    marginBottom: 2,
  },
  instructionText: {
    fontSize: 13,
    color: "#bcc6d6",
    lineHeight: 18,
  },
  exampleText: {
    marginTop: 4,
    fontSize: 12,
    color: "#9fb3d4",
    fontWeight: "600",
  },
  previewCard: {
    marginTop: 8,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: "#36404e",
    backgroundColor: "#202732",
    borderRadius: 10,
    padding: 10,
  },
  previewTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#d3d9e4",
  },
  previewHint: {
    fontSize: 13,
    color: "#b5bece",
    marginTop: 2,
    marginBottom: 8,
  },
  helperBlock: {
    color: "#b8c2d3",
    fontSize: 13,
    marginBottom: 10,
    lineHeight: 18,
  },
  reviewPickerBlock: {
    marginBottom: 8,
  },
  reviewPickerLabel: {
    fontSize: 13,
    color: "#c6cfde",
    fontWeight: "600",
    marginBottom: 2,
  },
  previewRowsWrap: {
    maxHeight: 220,
  },
  tableScrollContent: {
    paddingBottom: 4,
  },
  errorText: {
    color: "#e58a9f",
    marginBottom: 10,
    fontWeight: "600",
  },
  tableHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    gap: 8,
  },
  tableHeaderLarge: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    gap: 8,
  },
  colHeader: {
    fontSize: 12,
    fontWeight: "700",
    color: "#aab1be",
  },
  modeCol: {
    flex: 1.2,
  },
  smallCol: {
    flex: 1,
  },
  actionCol: {
    width: 90,
  },
  rowsWrap: {
    flex: 1,
  },
  rowsContent: {
    gap: 8,
    paddingBottom: 12,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  mobileRowCard: {
    borderWidth: 1,
    borderColor: "#36404e",
    borderRadius: 8,
    backgroundColor: "#181e28",
    paddingVertical: 8,
    paddingHorizontal: 10,
    gap: 6,
  },
  mobileFieldRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  mobileFieldLabel: {
    color: "#aab1be",
    fontSize: 12,
    fontWeight: "700",
    flexShrink: 0,
  },
  mobileFieldValue: {
    color: "#d4dae5",
    fontSize: 13,
    textAlign: "right",
    flexShrink: 1,
  },
  input: {
    height: 42,
    borderWidth: 1,
    borderColor: "#3b4452",
    borderRadius: 8,
    backgroundColor: "#131820",
    color: "#d5dbe6",
    paddingHorizontal: 10,
  },
  inputError: {
    borderColor: "#d96f89",
  },
  fieldErrorText: {
    color: "#f0a5b6",
    fontSize: 12,
    marginTop: -2,
  },
  searchInput: {
    height: 40,
    borderWidth: 1,
    borderColor: "#3b4452",
    borderRadius: 8,
    backgroundColor: "#131820",
    color: "#d5dbe6",
    paddingHorizontal: 10,
    marginBottom: 8,
  },
  previewCell: {
    minHeight: 34,
    borderWidth: 1,
    borderColor: "#3b4452",
    borderRadius: 8,
    backgroundColor: "#131820",
    paddingHorizontal: 10,
    paddingVertical: 8,
    color: "#d4dae5",
  },
  deleteButton: {
    width: 90,
    height: 42,
    borderRadius: 8,
    backgroundColor: "#7b3a4a",
    alignItems: "center",
    justifyContent: "center",
  },
  deleteButtonText: {
    color: "white",
    fontWeight: "700",
    fontSize: 13,
  },
  actionsRow: {
    marginTop: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  primaryButton: {
    flex: 1,
    height: 42,
    borderRadius: 8,
    backgroundColor: "#4f6b91",
    alignItems: "center",
    justifyContent: "center",
  },
  primaryActionButton: {
    flexGrow: 2,
  },
  secondaryActionButton: {
    flexGrow: 1,
  },
  railGenerateButton: {
    flexBasis: "100%",
    minHeight: 44,
    marginTop: 2,
  },
  primaryButtonDisabled: {
    backgroundColor: "#3f4f67",
  },
  primaryButtonText: {
    color: "#f1f4f8",
    fontWeight: "700",
  },
  stickyBar: {
    borderWidth: 1,
    borderColor: "#303642",
    borderRadius: 12,
    backgroundColor: "#1b1f27",
    padding: 12,
    gap: 8,
  },
  stickyMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  stickyActions: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  stickyMuted: {
    color: "#aeb7c6",
    fontSize: 12,
  },
  stickyWarning: {
    color: "#f3c27b",
    fontSize: 12,
    fontWeight: "700",
  },
  pendingApplyText: {
    color: "#f0a5b6",
    fontSize: 12,
    fontWeight: "700",
  },
});
