import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f3f6fb",
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 20,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 18,
    gap: 12,
  },
  header: {
    fontSize: 26,
    fontWeight: "700",
    color: "#111827",
  },
  centerWrap: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
  },
  helper: {
    color: "#4b5563",
    fontSize: 14,
  },
  card: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    padding: 16,
  },
  sectionTitle: {
    marginTop: 10,
    marginBottom: 8,
    fontSize: 14,
    fontWeight: "700",
    color: "#1f2937",
  },
  modePickerRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 8,
    marginBottom: 6,
  },
  modePickerButton: {
    paddingHorizontal: 12,
    height: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#f8fafc",
    alignItems: "center",
    justifyContent: "center",
  },
  modePickerButtonActive: {
    borderColor: "#2563eb",
    backgroundColor: "#dbeafe",
  },
  modePickerButtonText: {
    color: "#1f2937",
    fontWeight: "600",
    fontSize: 12,
  },
  modePickerButtonTextActive: {
    color: "#1d4ed8",
  },
  formulaGrid: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
    flexWrap: "wrap",
    marginBottom: 8,
  },
  formulaField: {
    gap: 6,
  },
  formulaLabel: {
    fontSize: 12,
    color: "#374151",
    fontWeight: "600",
  },
  formulaWide: {
    minWidth: 260,
    flexGrow: 1,
  },
  formulaCell: {
    minWidth: 120,
  },
  instructionCard: {
    borderWidth: 1,
    borderColor: "#dbeafe",
    backgroundColor: "#f8fbff",
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
    gap: 3,
  },
  instructionTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#1f2937",
    marginBottom: 2,
  },
  instructionText: {
    fontSize: 12,
    color: "#4b5563",
    lineHeight: 17,
  },
  exampleText: {
    marginTop: 4,
    fontSize: 12,
    color: "#1d4ed8",
    fontWeight: "600",
  },
  previewCard: {
    marginTop: 8,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: "#dbeafe",
    backgroundColor: "#f8fbff",
    borderRadius: 10,
    padding: 10,
  },
  previewTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1f2937",
  },
  previewHint: {
    fontSize: 12,
    color: "#4b5563",
    marginTop: 2,
    marginBottom: 8,
  },
  previewRowsWrap: {
    maxHeight: 220,
  },
  errorText: {
    color: "#dc2626",
    marginBottom: 10,
    fontWeight: "600",
  },
  tableHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    gap: 8,
  },
  tableHeaderLarge: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    gap: 8,
  },
  colHeader: {
    fontSize: 12,
    fontWeight: "700",
    color: "#4b5563",
  },
  modeCol: {
    flex: 1.2,
  },
  smallCol: {
    flex: 1,
  },
  actionCol: {
    width: 90,
  },
  rowsWrap: {
    flex: 1,
  },
  rowsContent: {
    gap: 8,
    paddingBottom: 12,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  input: {
    height: 42,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    backgroundColor: "#f9fafb",
    paddingHorizontal: 10,
  },
  previewCell: {
    minHeight: 34,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    backgroundColor: "#f9fafb",
    paddingHorizontal: 10,
    paddingVertical: 8,
    color: "#1f2937",
  },
  deleteButton: {
    width: 90,
    height: 42,
    borderRadius: 8,
    backgroundColor: "#ef4444",
    alignItems: "center",
    justifyContent: "center",
  },
  deleteButtonText: {
    color: "white",
    fontWeight: "700",
    fontSize: 13,
  },
  actionsRow: {
    marginTop: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  secondaryButton: {
    paddingHorizontal: 14,
    height: 40,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#f8fafc",
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryButtonText: {
    color: "#1f2937",
    fontWeight: "600",
  },
  primaryButton: {
    flex: 1,
    height: 42,
    borderRadius: 8,
    backgroundColor: "#2563eb",
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonDisabled: {
    backgroundColor: "#93c5fd",
  },
  primaryButtonText: {
    color: "#ffffff",
    fontWeight: "700",
  },
});
